name: frontend
description: "Online Banking System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  dio: ^5.4.2+1
  flutter_animate: ^4.5.0
  icons_plus: ^5.0.0
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  toastification: ^1.2.1
  animated_loading_border: ^0.0.2
  flutter_animated_button: ^2.0.3
  uuid: ^4.3.3
  animated_line_through: ^1.0.4
  animated_toggle_switch: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
